name: Check PR
on: 
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Use Node JS LTS
      uses: actions/setup-node@v4
      with:
        node-version: 20.x

    - name: Install npm dependencies
      run: npm install

    - name: Run build steps
      run: npm run build

    - name: Run default tests
      run: npm test
